export const USER_STATE_CHANGE = 'USER_STATE_CHANGE';
export const USER_COMPLETED_TASKS_CHANGE = 'USER_COMPLETED_TASKS_CHANGE';
export const UPDATE_FOCUS_TIME = 'UPDATE_FOCUS_TIME';
export const UPDATE_STATS = 'UPDATE_STATS';
